add a country.html
PUP-BSIT/exercise-14-avengears pull request #5
Opened 2024-06-04 15:51 UTC by ferolinojasmin

added a country.html

2024-06-04 15:59 UTC, nabayra-james requested changes

2024-06-04 15:59 UTC, nabayra-james commented on ferolino_jasmin/country.html
> +    <script src="countries.js"></script>
This is not the name of your js file. javascript.js is the appropriate file name.

2024-06-04 15:59 UTC, nabayra-james commented on ferolino_jasmin/javascript.js
> +  const countryInput = document.getElementById('countryInput').value;
### IDs should be written in snake case. All lower case separated by underscore.

Reference: https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g24da8de92d7_0_5

This also applies to lines 95 and 113 in your JS file.

2024-06-04 15:59 UTC, nabayra-james commented on ferolino_jasmin/country.html
> +    <input type="text" id="countryInput" placeholder="Enter a country">
### IDs should be written in snake case. All lower case separated by underscore.

Reference: https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g24da8de92d7_0_5

This also applies to lines 6, and 9.

2024-06-04 16:39 UTC, nabayra-james requested changes, later dismissed

2024-06-04 16:39 UTC, nabayra-james commented on ferolino_jasmin/country.html
> +    <div id="countrydetails">
### IDs should be written in snake case. All lower case separated by underscore.

This the appropriate id: country_details

Reference: https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g24da8de92d7_0_5

This also applies in line 17

2024-06-04 16:39 UTC, nabayra-james commented on ferolino_jasmin/country.html
> +    <script src=" javascript.js"></script>
### Remove unnecessary/excessive lines and spacing.

Reference: https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g25d18931cb7_3_0

No space in the script tag for the file name of your js.

2024-06-11 13:59 UTC, Japitana-JohnWalter approved these changes

2024-06-11 14:05 UTC, merged